### ISSUE TITLE
Incorrectly assuming there are more issues

### ISSUE THREAD

**Issue by rzadp** [paritytech/stale-issues-finder#19]
Here is a message in one of the channels:

<img width="525" alt="Screenshot 2023-06-13 at 11 04 18" src="https://github.com/paritytech/stale-issues-finder/assets/12039224/0a305485-e05f-465f-bbe9-ffd24440d83a">

It suggests that there are more than 8 issues, but the message only lists 2.

**Comment by Bullrich** [comment]
The issue is not with the stale issue finder but with the yaml file with a predefined message.

We would need to write a conditional string in bash which won't be pretty.

**Comment by rzadp** [comment]
I see, how about removing this message altogether, since it's not always correct?
https://github.com/paritytech/opstooling/pull/255
